spring:
  application:
    name: mcc-credit-disbursement-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost:5432}/${DB_NAME:mcc_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
server:
  port: ${SERVER_PORT:8082}
feign:
  clients:
    account:
      name: account-service
      url: http://localhost:8081/accounts
